/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUsersRouteImport } from './routes/api.users'
import { Route as ApiSessionRouteImport } from './routes/api.session'
import { Route as ApiReadyRouteImport } from './routes/api.ready'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiCompaniesRouteImport } from './routes/api.companies'
import { Route as AuthedCompaniesRouteImport } from './routes/_authed.companies'
import { Route as ApiProjectsProjectIdRouteImport } from './routes/api.projects.$projectId'
import { Route as ApiMembershipsCompaniesRouteImport } from './routes/api.memberships.companies'
import { Route as ApiMeDefaultCompanyRouteImport } from './routes/api.me.default-company'
import { Route as ApiDevSessionRouteImport } from './routes/api.dev.session'
import { Route as ApiDevResetSeedRouteImport } from './routes/api.dev.reset-seed'
import { Route as ApiCompaniesCompanyIdRouteImport } from './routes/api.companies.$companyId'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AuthedCCompanyIdRouteImport } from './routes/_authed.c.$companyId'
import { Route as ApiProjectsProjectIdTransactionsRouteImport } from './routes/api.projects.$projectId.transactions'
import { Route as ApiProjectsProjectIdSubCategoriesRouteImport } from './routes/api.projects.$projectId.sub-categories'
import { Route as ApiProjectsProjectIdReactivateRouteImport } from './routes/api.projects.$projectId.reactivate'
import { Route as ApiProjectsProjectIdMembershipsRouteImport } from './routes/api.projects.$projectId.memberships'
import { Route as ApiProjectsProjectIdDeactivateRouteImport } from './routes/api.projects.$projectId.deactivate'
import { Route as ApiProjectsProjectIdCategoriesRouteImport } from './routes/api.projects.$projectId.categories'
import { Route as ApiProjectsProjectIdBudgetsRouteImport } from './routes/api.projects.$projectId.budgets'
import { Route as ApiCompaniesCompanyIdUsersRouteImport } from './routes/api.companies.$companyId.users'
import { Route as ApiCompaniesCompanyIdReactivateRouteImport } from './routes/api.companies.$companyId.reactivate'
import { Route as ApiCompaniesCompanyIdProjectsRouteImport } from './routes/api.companies.$companyId.projects'
import { Route as ApiCompaniesCompanyIdMyProjectMembershipsRouteImport } from './routes/api.companies.$companyId.my-project-memberships'
import { Route as ApiCompaniesCompanyIdMembershipsRouteImport } from './routes/api.companies.$companyId.memberships'
import { Route as ApiCompaniesCompanyIdDeactivateRouteImport } from './routes/api.companies.$companyId.deactivate'
import { Route as ApiProjectsProjectIdTransactionsImportRouteImport } from './routes/api.projects.$projectId.transactions.import'
import { Route as ApiProjectsProjectIdTransactionsTxnIdRouteImport } from './routes/api.projects.$projectId.transactions.$txnId'
import { Route as ApiProjectsProjectIdSubCategoriesSubCategoryIdRouteImport } from './routes/api.projects.$projectId.sub-categories.$subCategoryId'
import { Route as ApiProjectsProjectIdCategoriesCategoryIdRouteImport } from './routes/api.projects.$projectId.categories.$categoryId'
import { Route as ApiProjectsProjectIdBudgetsBudgetIdRouteImport } from './routes/api.projects.$projectId.budgets.$budgetId'
import { Route as AuthedCCompanyIdPProjectIdRouteImport } from './routes/_authed.c.$companyId.p.$projectId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: '/api/ready',
  path: '/api/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompaniesRoute = ApiCompaniesRouteImport.update({
  id: '/api/companies',
  path: '/api/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCompaniesRoute = AuthedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiProjectsProjectIdRoute = ApiProjectsProjectIdRouteImport.update({
  id: '/api/projects/$projectId',
  path: '/api/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMembershipsCompaniesRoute = ApiMembershipsCompaniesRouteImport.update({
  id: '/api/memberships/companies',
  path: '/api/memberships/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeDefaultCompanyRoute = ApiMeDefaultCompanyRouteImport.update({
  id: '/api/me/default-company',
  path: '/api/me/default-company',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevSessionRoute = ApiDevSessionRouteImport.update({
  id: '/api/dev/session',
  path: '/api/dev/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevResetSeedRoute = ApiDevResetSeedRouteImport.update({
  id: '/api/dev/reset-seed',
  path: '/api/dev/reset-seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompaniesCompanyIdRoute = ApiCompaniesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => ApiCompaniesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCCompanyIdRoute = AuthedCCompanyIdRouteImport.update({
  id: '/c/$companyId',
  path: '/c/$companyId',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiProjectsProjectIdTransactionsRoute =
  ApiProjectsProjectIdTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiProjectsProjectIdSubCategoriesRoute =
  ApiProjectsProjectIdSubCategoriesRouteImport.update({
    id: '/sub-categories',
    path: '/sub-categories',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiProjectsProjectIdReactivateRoute =
  ApiProjectsProjectIdReactivateRouteImport.update({
    id: '/reactivate',
    path: '/reactivate',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiProjectsProjectIdMembershipsRoute =
  ApiProjectsProjectIdMembershipsRouteImport.update({
    id: '/memberships',
    path: '/memberships',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiProjectsProjectIdDeactivateRoute =
  ApiProjectsProjectIdDeactivateRouteImport.update({
    id: '/deactivate',
    path: '/deactivate',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiProjectsProjectIdCategoriesRoute =
  ApiProjectsProjectIdCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiProjectsProjectIdBudgetsRoute =
  ApiProjectsProjectIdBudgetsRouteImport.update({
    id: '/budgets',
    path: '/budgets',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiCompaniesCompanyIdUsersRoute =
  ApiCompaniesCompanyIdUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => ApiCompaniesCompanyIdRoute,
  } as any)
const ApiCompaniesCompanyIdReactivateRoute =
  ApiCompaniesCompanyIdReactivateRouteImport.update({
    id: '/reactivate',
    path: '/reactivate',
    getParentRoute: () => ApiCompaniesCompanyIdRoute,
  } as any)
const ApiCompaniesCompanyIdProjectsRoute =
  ApiCompaniesCompanyIdProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => ApiCompaniesCompanyIdRoute,
  } as any)
const ApiCompaniesCompanyIdMyProjectMembershipsRoute =
  ApiCompaniesCompanyIdMyProjectMembershipsRouteImport.update({
    id: '/my-project-memberships',
    path: '/my-project-memberships',
    getParentRoute: () => ApiCompaniesCompanyIdRoute,
  } as any)
const ApiCompaniesCompanyIdMembershipsRoute =
  ApiCompaniesCompanyIdMembershipsRouteImport.update({
    id: '/memberships',
    path: '/memberships',
    getParentRoute: () => ApiCompaniesCompanyIdRoute,
  } as any)
const ApiCompaniesCompanyIdDeactivateRoute =
  ApiCompaniesCompanyIdDeactivateRouteImport.update({
    id: '/deactivate',
    path: '/deactivate',
    getParentRoute: () => ApiCompaniesCompanyIdRoute,
  } as any)
const ApiProjectsProjectIdTransactionsImportRoute =
  ApiProjectsProjectIdTransactionsImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => ApiProjectsProjectIdTransactionsRoute,
  } as any)
const ApiProjectsProjectIdTransactionsTxnIdRoute =
  ApiProjectsProjectIdTransactionsTxnIdRouteImport.update({
    id: '/$txnId',
    path: '/$txnId',
    getParentRoute: () => ApiProjectsProjectIdTransactionsRoute,
  } as any)
const ApiProjectsProjectIdSubCategoriesSubCategoryIdRoute =
  ApiProjectsProjectIdSubCategoriesSubCategoryIdRouteImport.update({
    id: '/$subCategoryId',
    path: '/$subCategoryId',
    getParentRoute: () => ApiProjectsProjectIdSubCategoriesRoute,
  } as any)
const ApiProjectsProjectIdCategoriesCategoryIdRoute =
  ApiProjectsProjectIdCategoriesCategoryIdRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => ApiProjectsProjectIdCategoriesRoute,
  } as any)
const ApiProjectsProjectIdBudgetsBudgetIdRoute =
  ApiProjectsProjectIdBudgetsBudgetIdRouteImport.update({
    id: '/$budgetId',
    path: '/$budgetId',
    getParentRoute: () => ApiProjectsProjectIdBudgetsRoute,
  } as any)
const AuthedCCompanyIdPProjectIdRoute =
  AuthedCCompanyIdPProjectIdRouteImport.update({
    id: '/p/$projectId',
    path: '/p/$projectId',
    getParentRoute: () => AuthedCCompanyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/companies': typeof AuthedCompaniesRoute
  '/api/companies': typeof ApiCompaniesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/session': typeof ApiSessionRoute
  '/api/users': typeof ApiUsersRoute
  '/c/$companyId': typeof AuthedCCompanyIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/companies/$companyId': typeof ApiCompaniesCompanyIdRouteWithChildren
  '/api/dev/reset-seed': typeof ApiDevResetSeedRoute
  '/api/dev/session': typeof ApiDevSessionRoute
  '/api/me/default-company': typeof ApiMeDefaultCompanyRoute
  '/api/memberships/companies': typeof ApiMembershipsCompaniesRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/api/companies/$companyId/deactivate': typeof ApiCompaniesCompanyIdDeactivateRoute
  '/api/companies/$companyId/memberships': typeof ApiCompaniesCompanyIdMembershipsRoute
  '/api/companies/$companyId/my-project-memberships': typeof ApiCompaniesCompanyIdMyProjectMembershipsRoute
  '/api/companies/$companyId/projects': typeof ApiCompaniesCompanyIdProjectsRoute
  '/api/companies/$companyId/reactivate': typeof ApiCompaniesCompanyIdReactivateRoute
  '/api/companies/$companyId/users': typeof ApiCompaniesCompanyIdUsersRoute
  '/api/projects/$projectId/budgets': typeof ApiProjectsProjectIdBudgetsRouteWithChildren
  '/api/projects/$projectId/categories': typeof ApiProjectsProjectIdCategoriesRouteWithChildren
  '/api/projects/$projectId/deactivate': typeof ApiProjectsProjectIdDeactivateRoute
  '/api/projects/$projectId/memberships': typeof ApiProjectsProjectIdMembershipsRoute
  '/api/projects/$projectId/reactivate': typeof ApiProjectsProjectIdReactivateRoute
  '/api/projects/$projectId/sub-categories': typeof ApiProjectsProjectIdSubCategoriesRouteWithChildren
  '/api/projects/$projectId/transactions': typeof ApiProjectsProjectIdTransactionsRouteWithChildren
  '/c/$companyId/p/$projectId': typeof AuthedCCompanyIdPProjectIdRoute
  '/api/projects/$projectId/budgets/$budgetId': typeof ApiProjectsProjectIdBudgetsBudgetIdRoute
  '/api/projects/$projectId/categories/$categoryId': typeof ApiProjectsProjectIdCategoriesCategoryIdRoute
  '/api/projects/$projectId/sub-categories/$subCategoryId': typeof ApiProjectsProjectIdSubCategoriesSubCategoryIdRoute
  '/api/projects/$projectId/transactions/$txnId': typeof ApiProjectsProjectIdTransactionsTxnIdRoute
  '/api/projects/$projectId/transactions/import': typeof ApiProjectsProjectIdTransactionsImportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/companies': typeof AuthedCompaniesRoute
  '/api/companies': typeof ApiCompaniesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/session': typeof ApiSessionRoute
  '/api/users': typeof ApiUsersRoute
  '/c/$companyId': typeof AuthedCCompanyIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/companies/$companyId': typeof ApiCompaniesCompanyIdRouteWithChildren
  '/api/dev/reset-seed': typeof ApiDevResetSeedRoute
  '/api/dev/session': typeof ApiDevSessionRoute
  '/api/me/default-company': typeof ApiMeDefaultCompanyRoute
  '/api/memberships/companies': typeof ApiMembershipsCompaniesRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/api/companies/$companyId/deactivate': typeof ApiCompaniesCompanyIdDeactivateRoute
  '/api/companies/$companyId/memberships': typeof ApiCompaniesCompanyIdMembershipsRoute
  '/api/companies/$companyId/my-project-memberships': typeof ApiCompaniesCompanyIdMyProjectMembershipsRoute
  '/api/companies/$companyId/projects': typeof ApiCompaniesCompanyIdProjectsRoute
  '/api/companies/$companyId/reactivate': typeof ApiCompaniesCompanyIdReactivateRoute
  '/api/companies/$companyId/users': typeof ApiCompaniesCompanyIdUsersRoute
  '/api/projects/$projectId/budgets': typeof ApiProjectsProjectIdBudgetsRouteWithChildren
  '/api/projects/$projectId/categories': typeof ApiProjectsProjectIdCategoriesRouteWithChildren
  '/api/projects/$projectId/deactivate': typeof ApiProjectsProjectIdDeactivateRoute
  '/api/projects/$projectId/memberships': typeof ApiProjectsProjectIdMembershipsRoute
  '/api/projects/$projectId/reactivate': typeof ApiProjectsProjectIdReactivateRoute
  '/api/projects/$projectId/sub-categories': typeof ApiProjectsProjectIdSubCategoriesRouteWithChildren
  '/api/projects/$projectId/transactions': typeof ApiProjectsProjectIdTransactionsRouteWithChildren
  '/c/$companyId/p/$projectId': typeof AuthedCCompanyIdPProjectIdRoute
  '/api/projects/$projectId/budgets/$budgetId': typeof ApiProjectsProjectIdBudgetsBudgetIdRoute
  '/api/projects/$projectId/categories/$categoryId': typeof ApiProjectsProjectIdCategoriesCategoryIdRoute
  '/api/projects/$projectId/sub-categories/$subCategoryId': typeof ApiProjectsProjectIdSubCategoriesSubCategoryIdRoute
  '/api/projects/$projectId/transactions/$txnId': typeof ApiProjectsProjectIdTransactionsTxnIdRoute
  '/api/projects/$projectId/transactions/import': typeof ApiProjectsProjectIdTransactionsImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/companies': typeof AuthedCompaniesRoute
  '/api/companies': typeof ApiCompaniesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/session': typeof ApiSessionRoute
  '/api/users': typeof ApiUsersRoute
  '/_authed/c/$companyId': typeof AuthedCCompanyIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/companies/$companyId': typeof ApiCompaniesCompanyIdRouteWithChildren
  '/api/dev/reset-seed': typeof ApiDevResetSeedRoute
  '/api/dev/session': typeof ApiDevSessionRoute
  '/api/me/default-company': typeof ApiMeDefaultCompanyRoute
  '/api/memberships/companies': typeof ApiMembershipsCompaniesRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/api/companies/$companyId/deactivate': typeof ApiCompaniesCompanyIdDeactivateRoute
  '/api/companies/$companyId/memberships': typeof ApiCompaniesCompanyIdMembershipsRoute
  '/api/companies/$companyId/my-project-memberships': typeof ApiCompaniesCompanyIdMyProjectMembershipsRoute
  '/api/companies/$companyId/projects': typeof ApiCompaniesCompanyIdProjectsRoute
  '/api/companies/$companyId/reactivate': typeof ApiCompaniesCompanyIdReactivateRoute
  '/api/companies/$companyId/users': typeof ApiCompaniesCompanyIdUsersRoute
  '/api/projects/$projectId/budgets': typeof ApiProjectsProjectIdBudgetsRouteWithChildren
  '/api/projects/$projectId/categories': typeof ApiProjectsProjectIdCategoriesRouteWithChildren
  '/api/projects/$projectId/deactivate': typeof ApiProjectsProjectIdDeactivateRoute
  '/api/projects/$projectId/memberships': typeof ApiProjectsProjectIdMembershipsRoute
  '/api/projects/$projectId/reactivate': typeof ApiProjectsProjectIdReactivateRoute
  '/api/projects/$projectId/sub-categories': typeof ApiProjectsProjectIdSubCategoriesRouteWithChildren
  '/api/projects/$projectId/transactions': typeof ApiProjectsProjectIdTransactionsRouteWithChildren
  '/_authed/c/$companyId/p/$projectId': typeof AuthedCCompanyIdPProjectIdRoute
  '/api/projects/$projectId/budgets/$budgetId': typeof ApiProjectsProjectIdBudgetsBudgetIdRoute
  '/api/projects/$projectId/categories/$categoryId': typeof ApiProjectsProjectIdCategoriesCategoryIdRoute
  '/api/projects/$projectId/sub-categories/$subCategoryId': typeof ApiProjectsProjectIdSubCategoriesSubCategoryIdRoute
  '/api/projects/$projectId/transactions/$txnId': typeof ApiProjectsProjectIdTransactionsTxnIdRoute
  '/api/projects/$projectId/transactions/import': typeof ApiProjectsProjectIdTransactionsImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/companies'
    | '/api/companies'
    | '/api/health'
    | '/api/ready'
    | '/api/session'
    | '/api/users'
    | '/c/$companyId'
    | '/api/auth/$'
    | '/api/companies/$companyId'
    | '/api/dev/reset-seed'
    | '/api/dev/session'
    | '/api/me/default-company'
    | '/api/memberships/companies'
    | '/api/projects/$projectId'
    | '/api/companies/$companyId/deactivate'
    | '/api/companies/$companyId/memberships'
    | '/api/companies/$companyId/my-project-memberships'
    | '/api/companies/$companyId/projects'
    | '/api/companies/$companyId/reactivate'
    | '/api/companies/$companyId/users'
    | '/api/projects/$projectId/budgets'
    | '/api/projects/$projectId/categories'
    | '/api/projects/$projectId/deactivate'
    | '/api/projects/$projectId/memberships'
    | '/api/projects/$projectId/reactivate'
    | '/api/projects/$projectId/sub-categories'
    | '/api/projects/$projectId/transactions'
    | '/c/$companyId/p/$projectId'
    | '/api/projects/$projectId/budgets/$budgetId'
    | '/api/projects/$projectId/categories/$categoryId'
    | '/api/projects/$projectId/sub-categories/$subCategoryId'
    | '/api/projects/$projectId/transactions/$txnId'
    | '/api/projects/$projectId/transactions/import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/companies'
    | '/api/companies'
    | '/api/health'
    | '/api/ready'
    | '/api/session'
    | '/api/users'
    | '/c/$companyId'
    | '/api/auth/$'
    | '/api/companies/$companyId'
    | '/api/dev/reset-seed'
    | '/api/dev/session'
    | '/api/me/default-company'
    | '/api/memberships/companies'
    | '/api/projects/$projectId'
    | '/api/companies/$companyId/deactivate'
    | '/api/companies/$companyId/memberships'
    | '/api/companies/$companyId/my-project-memberships'
    | '/api/companies/$companyId/projects'
    | '/api/companies/$companyId/reactivate'
    | '/api/companies/$companyId/users'
    | '/api/projects/$projectId/budgets'
    | '/api/projects/$projectId/categories'
    | '/api/projects/$projectId/deactivate'
    | '/api/projects/$projectId/memberships'
    | '/api/projects/$projectId/reactivate'
    | '/api/projects/$projectId/sub-categories'
    | '/api/projects/$projectId/transactions'
    | '/c/$companyId/p/$projectId'
    | '/api/projects/$projectId/budgets/$budgetId'
    | '/api/projects/$projectId/categories/$categoryId'
    | '/api/projects/$projectId/sub-categories/$subCategoryId'
    | '/api/projects/$projectId/transactions/$txnId'
    | '/api/projects/$projectId/transactions/import'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/companies'
    | '/api/companies'
    | '/api/health'
    | '/api/ready'
    | '/api/session'
    | '/api/users'
    | '/_authed/c/$companyId'
    | '/api/auth/$'
    | '/api/companies/$companyId'
    | '/api/dev/reset-seed'
    | '/api/dev/session'
    | '/api/me/default-company'
    | '/api/memberships/companies'
    | '/api/projects/$projectId'
    | '/api/companies/$companyId/deactivate'
    | '/api/companies/$companyId/memberships'
    | '/api/companies/$companyId/my-project-memberships'
    | '/api/companies/$companyId/projects'
    | '/api/companies/$companyId/reactivate'
    | '/api/companies/$companyId/users'
    | '/api/projects/$projectId/budgets'
    | '/api/projects/$projectId/categories'
    | '/api/projects/$projectId/deactivate'
    | '/api/projects/$projectId/memberships'
    | '/api/projects/$projectId/reactivate'
    | '/api/projects/$projectId/sub-categories'
    | '/api/projects/$projectId/transactions'
    | '/_authed/c/$companyId/p/$projectId'
    | '/api/projects/$projectId/budgets/$budgetId'
    | '/api/projects/$projectId/categories/$categoryId'
    | '/api/projects/$projectId/sub-categories/$subCategoryId'
    | '/api/projects/$projectId/transactions/$txnId'
    | '/api/projects/$projectId/transactions/import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiCompaniesRoute: typeof ApiCompaniesRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReadyRoute: typeof ApiReadyRoute
  ApiSessionRoute: typeof ApiSessionRoute
  ApiUsersRoute: typeof ApiUsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDevResetSeedRoute: typeof ApiDevResetSeedRoute
  ApiDevSessionRoute: typeof ApiDevSessionRoute
  ApiMeDefaultCompanyRoute: typeof ApiMeDefaultCompanyRoute
  ApiMembershipsCompaniesRoute: typeof ApiMembershipsCompaniesRoute
  ApiProjectsProjectIdRoute: typeof ApiProjectsProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ready': {
      id: '/api/ready'
      path: '/api/ready'
      fullPath: '/api/ready'
      preLoaderRoute: typeof ApiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/companies': {
      id: '/api/companies'
      path: '/api/companies'
      fullPath: '/api/companies'
      preLoaderRoute: typeof ApiCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/companies': {
      id: '/_authed/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthedCompaniesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/projects/$projectId': {
      id: '/api/projects/$projectId'
      path: '/api/projects/$projectId'
      fullPath: '/api/projects/$projectId'
      preLoaderRoute: typeof ApiProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memberships/companies': {
      id: '/api/memberships/companies'
      path: '/api/memberships/companies'
      fullPath: '/api/memberships/companies'
      preLoaderRoute: typeof ApiMembershipsCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/default-company': {
      id: '/api/me/default-company'
      path: '/api/me/default-company'
      fullPath: '/api/me/default-company'
      preLoaderRoute: typeof ApiMeDefaultCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/session': {
      id: '/api/dev/session'
      path: '/api/dev/session'
      fullPath: '/api/dev/session'
      preLoaderRoute: typeof ApiDevSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/reset-seed': {
      id: '/api/dev/reset-seed'
      path: '/api/dev/reset-seed'
      fullPath: '/api/dev/reset-seed'
      preLoaderRoute: typeof ApiDevResetSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/companies/$companyId': {
      id: '/api/companies/$companyId'
      path: '/$companyId'
      fullPath: '/api/companies/$companyId'
      preLoaderRoute: typeof ApiCompaniesCompanyIdRouteImport
      parentRoute: typeof ApiCompaniesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/c/$companyId': {
      id: '/_authed/c/$companyId'
      path: '/c/$companyId'
      fullPath: '/c/$companyId'
      preLoaderRoute: typeof AuthedCCompanyIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/projects/$projectId/transactions': {
      id: '/api/projects/$projectId/transactions'
      path: '/transactions'
      fullPath: '/api/projects/$projectId/transactions'
      preLoaderRoute: typeof ApiProjectsProjectIdTransactionsRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/projects/$projectId/sub-categories': {
      id: '/api/projects/$projectId/sub-categories'
      path: '/sub-categories'
      fullPath: '/api/projects/$projectId/sub-categories'
      preLoaderRoute: typeof ApiProjectsProjectIdSubCategoriesRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/projects/$projectId/reactivate': {
      id: '/api/projects/$projectId/reactivate'
      path: '/reactivate'
      fullPath: '/api/projects/$projectId/reactivate'
      preLoaderRoute: typeof ApiProjectsProjectIdReactivateRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/projects/$projectId/memberships': {
      id: '/api/projects/$projectId/memberships'
      path: '/memberships'
      fullPath: '/api/projects/$projectId/memberships'
      preLoaderRoute: typeof ApiProjectsProjectIdMembershipsRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/projects/$projectId/deactivate': {
      id: '/api/projects/$projectId/deactivate'
      path: '/deactivate'
      fullPath: '/api/projects/$projectId/deactivate'
      preLoaderRoute: typeof ApiProjectsProjectIdDeactivateRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/projects/$projectId/categories': {
      id: '/api/projects/$projectId/categories'
      path: '/categories'
      fullPath: '/api/projects/$projectId/categories'
      preLoaderRoute: typeof ApiProjectsProjectIdCategoriesRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/projects/$projectId/budgets': {
      id: '/api/projects/$projectId/budgets'
      path: '/budgets'
      fullPath: '/api/projects/$projectId/budgets'
      preLoaderRoute: typeof ApiProjectsProjectIdBudgetsRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/companies/$companyId/users': {
      id: '/api/companies/$companyId/users'
      path: '/users'
      fullPath: '/api/companies/$companyId/users'
      preLoaderRoute: typeof ApiCompaniesCompanyIdUsersRouteImport
      parentRoute: typeof ApiCompaniesCompanyIdRoute
    }
    '/api/companies/$companyId/reactivate': {
      id: '/api/companies/$companyId/reactivate'
      path: '/reactivate'
      fullPath: '/api/companies/$companyId/reactivate'
      preLoaderRoute: typeof ApiCompaniesCompanyIdReactivateRouteImport
      parentRoute: typeof ApiCompaniesCompanyIdRoute
    }
    '/api/companies/$companyId/projects': {
      id: '/api/companies/$companyId/projects'
      path: '/projects'
      fullPath: '/api/companies/$companyId/projects'
      preLoaderRoute: typeof ApiCompaniesCompanyIdProjectsRouteImport
      parentRoute: typeof ApiCompaniesCompanyIdRoute
    }
    '/api/companies/$companyId/my-project-memberships': {
      id: '/api/companies/$companyId/my-project-memberships'
      path: '/my-project-memberships'
      fullPath: '/api/companies/$companyId/my-project-memberships'
      preLoaderRoute: typeof ApiCompaniesCompanyIdMyProjectMembershipsRouteImport
      parentRoute: typeof ApiCompaniesCompanyIdRoute
    }
    '/api/companies/$companyId/memberships': {
      id: '/api/companies/$companyId/memberships'
      path: '/memberships'
      fullPath: '/api/companies/$companyId/memberships'
      preLoaderRoute: typeof ApiCompaniesCompanyIdMembershipsRouteImport
      parentRoute: typeof ApiCompaniesCompanyIdRoute
    }
    '/api/companies/$companyId/deactivate': {
      id: '/api/companies/$companyId/deactivate'
      path: '/deactivate'
      fullPath: '/api/companies/$companyId/deactivate'
      preLoaderRoute: typeof ApiCompaniesCompanyIdDeactivateRouteImport
      parentRoute: typeof ApiCompaniesCompanyIdRoute
    }
    '/api/projects/$projectId/transactions/import': {
      id: '/api/projects/$projectId/transactions/import'
      path: '/import'
      fullPath: '/api/projects/$projectId/transactions/import'
      preLoaderRoute: typeof ApiProjectsProjectIdTransactionsImportRouteImport
      parentRoute: typeof ApiProjectsProjectIdTransactionsRoute
    }
    '/api/projects/$projectId/transactions/$txnId': {
      id: '/api/projects/$projectId/transactions/$txnId'
      path: '/$txnId'
      fullPath: '/api/projects/$projectId/transactions/$txnId'
      preLoaderRoute: typeof ApiProjectsProjectIdTransactionsTxnIdRouteImport
      parentRoute: typeof ApiProjectsProjectIdTransactionsRoute
    }
    '/api/projects/$projectId/sub-categories/$subCategoryId': {
      id: '/api/projects/$projectId/sub-categories/$subCategoryId'
      path: '/$subCategoryId'
      fullPath: '/api/projects/$projectId/sub-categories/$subCategoryId'
      preLoaderRoute: typeof ApiProjectsProjectIdSubCategoriesSubCategoryIdRouteImport
      parentRoute: typeof ApiProjectsProjectIdSubCategoriesRoute
    }
    '/api/projects/$projectId/categories/$categoryId': {
      id: '/api/projects/$projectId/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/api/projects/$projectId/categories/$categoryId'
      preLoaderRoute: typeof ApiProjectsProjectIdCategoriesCategoryIdRouteImport
      parentRoute: typeof ApiProjectsProjectIdCategoriesRoute
    }
    '/api/projects/$projectId/budgets/$budgetId': {
      id: '/api/projects/$projectId/budgets/$budgetId'
      path: '/$budgetId'
      fullPath: '/api/projects/$projectId/budgets/$budgetId'
      preLoaderRoute: typeof ApiProjectsProjectIdBudgetsBudgetIdRouteImport
      parentRoute: typeof ApiProjectsProjectIdBudgetsRoute
    }
    '/_authed/c/$companyId/p/$projectId': {
      id: '/_authed/c/$companyId/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/c/$companyId/p/$projectId'
      preLoaderRoute: typeof AuthedCCompanyIdPProjectIdRouteImport
      parentRoute: typeof AuthedCCompanyIdRoute
    }
  }
}

interface AuthedCCompanyIdRouteChildren {
  AuthedCCompanyIdPProjectIdRoute: typeof AuthedCCompanyIdPProjectIdRoute
}

const AuthedCCompanyIdRouteChildren: AuthedCCompanyIdRouteChildren = {
  AuthedCCompanyIdPProjectIdRoute: AuthedCCompanyIdPProjectIdRoute,
}

const AuthedCCompanyIdRouteWithChildren =
  AuthedCCompanyIdRoute._addFileChildren(AuthedCCompanyIdRouteChildren)

interface AuthedRouteChildren {
  AuthedCompaniesRoute: typeof AuthedCompaniesRoute
  AuthedCCompanyIdRoute: typeof AuthedCCompanyIdRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCompaniesRoute: AuthedCompaniesRoute,
  AuthedCCompanyIdRoute: AuthedCCompanyIdRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface ApiCompaniesCompanyIdRouteChildren {
  ApiCompaniesCompanyIdDeactivateRoute: typeof ApiCompaniesCompanyIdDeactivateRoute
  ApiCompaniesCompanyIdMembershipsRoute: typeof ApiCompaniesCompanyIdMembershipsRoute
  ApiCompaniesCompanyIdMyProjectMembershipsRoute: typeof ApiCompaniesCompanyIdMyProjectMembershipsRoute
  ApiCompaniesCompanyIdProjectsRoute: typeof ApiCompaniesCompanyIdProjectsRoute
  ApiCompaniesCompanyIdReactivateRoute: typeof ApiCompaniesCompanyIdReactivateRoute
  ApiCompaniesCompanyIdUsersRoute: typeof ApiCompaniesCompanyIdUsersRoute
}

const ApiCompaniesCompanyIdRouteChildren: ApiCompaniesCompanyIdRouteChildren = {
  ApiCompaniesCompanyIdDeactivateRoute: ApiCompaniesCompanyIdDeactivateRoute,
  ApiCompaniesCompanyIdMembershipsRoute: ApiCompaniesCompanyIdMembershipsRoute,
  ApiCompaniesCompanyIdMyProjectMembershipsRoute:
    ApiCompaniesCompanyIdMyProjectMembershipsRoute,
  ApiCompaniesCompanyIdProjectsRoute: ApiCompaniesCompanyIdProjectsRoute,
  ApiCompaniesCompanyIdReactivateRoute: ApiCompaniesCompanyIdReactivateRoute,
  ApiCompaniesCompanyIdUsersRoute: ApiCompaniesCompanyIdUsersRoute,
}

const ApiCompaniesCompanyIdRouteWithChildren =
  ApiCompaniesCompanyIdRoute._addFileChildren(
    ApiCompaniesCompanyIdRouteChildren,
  )

interface ApiCompaniesRouteChildren {
  ApiCompaniesCompanyIdRoute: typeof ApiCompaniesCompanyIdRouteWithChildren
}

const ApiCompaniesRouteChildren: ApiCompaniesRouteChildren = {
  ApiCompaniesCompanyIdRoute: ApiCompaniesCompanyIdRouteWithChildren,
}

const ApiCompaniesRouteWithChildren = ApiCompaniesRoute._addFileChildren(
  ApiCompaniesRouteChildren,
)

interface ApiProjectsProjectIdBudgetsRouteChildren {
  ApiProjectsProjectIdBudgetsBudgetIdRoute: typeof ApiProjectsProjectIdBudgetsBudgetIdRoute
}

const ApiProjectsProjectIdBudgetsRouteChildren: ApiProjectsProjectIdBudgetsRouteChildren =
  {
    ApiProjectsProjectIdBudgetsBudgetIdRoute:
      ApiProjectsProjectIdBudgetsBudgetIdRoute,
  }

const ApiProjectsProjectIdBudgetsRouteWithChildren =
  ApiProjectsProjectIdBudgetsRoute._addFileChildren(
    ApiProjectsProjectIdBudgetsRouteChildren,
  )

interface ApiProjectsProjectIdCategoriesRouteChildren {
  ApiProjectsProjectIdCategoriesCategoryIdRoute: typeof ApiProjectsProjectIdCategoriesCategoryIdRoute
}

const ApiProjectsProjectIdCategoriesRouteChildren: ApiProjectsProjectIdCategoriesRouteChildren =
  {
    ApiProjectsProjectIdCategoriesCategoryIdRoute:
      ApiProjectsProjectIdCategoriesCategoryIdRoute,
  }

const ApiProjectsProjectIdCategoriesRouteWithChildren =
  ApiProjectsProjectIdCategoriesRoute._addFileChildren(
    ApiProjectsProjectIdCategoriesRouteChildren,
  )

interface ApiProjectsProjectIdSubCategoriesRouteChildren {
  ApiProjectsProjectIdSubCategoriesSubCategoryIdRoute: typeof ApiProjectsProjectIdSubCategoriesSubCategoryIdRoute
}

const ApiProjectsProjectIdSubCategoriesRouteChildren: ApiProjectsProjectIdSubCategoriesRouteChildren =
  {
    ApiProjectsProjectIdSubCategoriesSubCategoryIdRoute:
      ApiProjectsProjectIdSubCategoriesSubCategoryIdRoute,
  }

const ApiProjectsProjectIdSubCategoriesRouteWithChildren =
  ApiProjectsProjectIdSubCategoriesRoute._addFileChildren(
    ApiProjectsProjectIdSubCategoriesRouteChildren,
  )

interface ApiProjectsProjectIdTransactionsRouteChildren {
  ApiProjectsProjectIdTransactionsTxnIdRoute: typeof ApiProjectsProjectIdTransactionsTxnIdRoute
  ApiProjectsProjectIdTransactionsImportRoute: typeof ApiProjectsProjectIdTransactionsImportRoute
}

const ApiProjectsProjectIdTransactionsRouteChildren: ApiProjectsProjectIdTransactionsRouteChildren =
  {
    ApiProjectsProjectIdTransactionsTxnIdRoute:
      ApiProjectsProjectIdTransactionsTxnIdRoute,
    ApiProjectsProjectIdTransactionsImportRoute:
      ApiProjectsProjectIdTransactionsImportRoute,
  }

const ApiProjectsProjectIdTransactionsRouteWithChildren =
  ApiProjectsProjectIdTransactionsRoute._addFileChildren(
    ApiProjectsProjectIdTransactionsRouteChildren,
  )

interface ApiProjectsProjectIdRouteChildren {
  ApiProjectsProjectIdBudgetsRoute: typeof ApiProjectsProjectIdBudgetsRouteWithChildren
  ApiProjectsProjectIdCategoriesRoute: typeof ApiProjectsProjectIdCategoriesRouteWithChildren
  ApiProjectsProjectIdDeactivateRoute: typeof ApiProjectsProjectIdDeactivateRoute
  ApiProjectsProjectIdMembershipsRoute: typeof ApiProjectsProjectIdMembershipsRoute
  ApiProjectsProjectIdReactivateRoute: typeof ApiProjectsProjectIdReactivateRoute
  ApiProjectsProjectIdSubCategoriesRoute: typeof ApiProjectsProjectIdSubCategoriesRouteWithChildren
  ApiProjectsProjectIdTransactionsRoute: typeof ApiProjectsProjectIdTransactionsRouteWithChildren
}

const ApiProjectsProjectIdRouteChildren: ApiProjectsProjectIdRouteChildren = {
  ApiProjectsProjectIdBudgetsRoute:
    ApiProjectsProjectIdBudgetsRouteWithChildren,
  ApiProjectsProjectIdCategoriesRoute:
    ApiProjectsProjectIdCategoriesRouteWithChildren,
  ApiProjectsProjectIdDeactivateRoute: ApiProjectsProjectIdDeactivateRoute,
  ApiProjectsProjectIdMembershipsRoute: ApiProjectsProjectIdMembershipsRoute,
  ApiProjectsProjectIdReactivateRoute: ApiProjectsProjectIdReactivateRoute,
  ApiProjectsProjectIdSubCategoriesRoute:
    ApiProjectsProjectIdSubCategoriesRouteWithChildren,
  ApiProjectsProjectIdTransactionsRoute:
    ApiProjectsProjectIdTransactionsRouteWithChildren,
}

const ApiProjectsProjectIdRouteWithChildren =
  ApiProjectsProjectIdRoute._addFileChildren(ApiProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiCompaniesRoute: ApiCompaniesRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiReadyRoute: ApiReadyRoute,
  ApiSessionRoute: ApiSessionRoute,
  ApiUsersRoute: ApiUsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDevResetSeedRoute: ApiDevResetSeedRoute,
  ApiDevSessionRoute: ApiDevSessionRoute,
  ApiMeDefaultCompanyRoute: ApiMeDefaultCompanyRoute,
  ApiMembershipsCompaniesRoute: ApiMembershipsCompaniesRoute,
  ApiProjectsProjectIdRoute: ApiProjectsProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
